name: Unit tests 🧪
on: [push]
permissions: write-all

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - run: npm ci
      - run: npm run test:unit
      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Jest tests
          path: junit.xml
          reporter: jest-junit
